# @Time    : 2024/4/1 13:41
# @Author  : zhangchenming
DATA_PATH_DICT = {
    'SceneFlowDataset': '/file_system/vepfs/public_data/SceneFlow',
    'FlyingThings3DSubsetDataset': '/mnt/nas/algorithm/chenming.zhang/dataset/SceneFlow',
    'KittiDataset12': '/file_system/vepfs/public_data/stereo/kitti12',
    'KittiDataset15': '/file_system/vepfs/public_data/stereo/kitti15',
    'DrivingDataset': '/mnt/nas/algorithm/chenming.zhang/dataset/DrivingStereo',
    'MiddleburyDataset': '/file_system/vepfs/public_data/stereo/Middlebury/',
    'ETH3DDataset': '/file_system/vepfs/public_data/stereo/eth3d',
    'ArgoverseDataset': '/file_system/vepfs/public_data/stereo/argovers1_1',
    'CREStereoDataset': '/file_system/vepfs/public_data/stereo/CREStereoData',
    'FallingThingsDataset': '/file_system/vepfs/public_data/stereo/FallingThings',
    'InStereo2KDataset': '/file_system/vepfs/public_data/stereo/InStereo2K',
    'SintelDataset': '/file_system/vepfs/public_data/stereo/Sintel',
    'TartanAirDataset': '/file_system/vepfs/public_data/stereo/tartanair',
    'SpringDataset': '/file_system/vepfs/public_data/stereo/spring',
    'VirtualKitti2Dataset': '/file_system/vepfs/public_data/stereo/virtualkitti2',
    'UnrealStereo4KDataset': '/file_system/vepfs/public_data/stereo/UnrealStereo4K',
    'CarlaDataset': '/file_system/vepfs/public_data/stereo/StereoFromCarlaV2',
    'FoundationStereoDataset': '/file_system/vepfs/public_data/stereo/foundationstereo',
    'DynamicReplicaDataset': '/file_system/vepfs/public_data/stereo/dynamic_stereo',
    'MonoDataset': '/file_system/vepfs/public_data/depthAnythingData',
    'RealfillDataset': '/file_system/vepfs/public_data/depthAnythingData',
}
