data_cfg:
  name: KITTI2012
  root: data/kitti12
  train_list: datasets/kitti12/kitti12_train165.txt
  val_list: datasets/kitti12/kitti12_val29.txt
  test_list: datasets/kitti1/kitti12_test.txt
  num_workers: 8

  transform:
    train:
      - type: RandomCrop
        size: [ 256, 512 ]
      #- type: RandomHorizontalFlip
      #  prob: 0.5
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    test:
      - type: StereoPad
        size: [ 384, 1248 ]
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]


model_cfg:
  model: CFNet
  find_unused_parameters: true
  replace_mish: false # Replace Mish with ReLU in the first 20 epochs

  base_config:
    max_disp: 256


optimizer_cfg:
  solver: RMSprop
  lr: 0.001


loss_cfg:
  - log_prefix: disp
    type: Weighted_Smooth_l1_Loss
    loss_term_weight: 1
    weights: [0.25, 0.35, 0.5, 0.5, 0.7, 1.0, 1.0, 1.4, 2]


scheduler_cfg:
  scheduler: MultiStepLR
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 6000
    - 8500

  warmup:
    type: LinearWarmup
    warmup_period: 500


trainer_cfg:
  save_name: CFNet_KITTI12
#  restore_hint: './output/SceneFlow/CFNet/CFNet_SceneFlow/checkpoints/CFNet_SceneFlow-00801.pt'
  restore_hint: 2200
  restore_ckpt_strict: true
  log_iter: 10
  with_test: true
  enable_float16: false
  sync_BN: true
  save_iter: 200
  total_iter: 150000
  total_epoch: 400
  optimizer_reset: false
  scheduler_reset: false

  sampler:
    # type: BasicStereoSampler
    batch_shuffle: true
    batch_size: 4


evaluator_cfg:
  eval_func: OpenStereoEvaluator
  save_name: CFNet_KITTI12
  restore_hint: 0
  metric:
    - d1_all
    - epe
    - thres_1
    - thres_2
    - thres_3
  restore_ckpt_strict: true
  enable_float16: false
  sampler:
    type: BasicStereoSampler
    batch_shuffle: false
    batch_size: 1
