data_cfg:
  name: FlyingThings3DSubset
  root: data/SceneFlow/FlyingThings3D_subset
  train_list: datasets/sceneflow/FlyingThings3D_subset_train.txt
  val_list: datasets/sceneflow/FlyingThings3D_subset_val.txt
  test_list: datasets/sceneflow/FlyingThings3D_subset_val.txt
  num_workers: 4

  batch_uniform: false
  #  random_type: range
  #  w_range: [ 0.5, 2.0 ]
  #  h_range: [ 0.5, 2.0 ]
  random_type: choice
  h_range: [ 256, 288, 320, 352 ]
  w_range: [ 480, 512, 544, 576 ]

  transform:
    train:
      - type: RandomCrop
        size: [ 256, 512 ]
#      - type: RandomHorizontalFlip
#        prob: 0.5
#      - type: GetValidDispNOcc
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    test:
      - type: CenterCrop
        size: [ 256, 512 ]
      - type: GetValidDispNOcc
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]



model_cfg:
  model: PSMNet

  base_config:
    max_disp: 192

  # Backbone
  backbone_cfg:
    type: PSMNet

  # VolumeCostProcessor
  cost_processor_cfg:
    type: PSMCostProcessor

  # DispProcessor
  disp_processor_cfg:
    type: PSMDispProcessor


optimizer_cfg:
  solver: RMSprop
  lr: 0.00001

loss_cfg:
  - log_prefix: disp
    loss_term_weight: 1
    type: Weighted_Smooth_l1_Loss
    weights: [ 0.5, 0.7, 1.0 ]


scheduler_cfg:
  scheduler: MultiStepLR
  gamma: 1
  milestones: # Learning Rate Reduction at each milestones
    - 25000

trainer_cfg:
  save_name: PSMNet_SceneFlow
  restore_hint: 0
  restore_ckpt_strict: true
  log_iter: 10
  with_test: true
  enable_float16: true
  save_iter: 2000
  sync_BN: true
  total_iter: 20000
  total_epoch: 20
  optimizer_reset: true
  scheduler_reset: false
  sampler:
    # type: DistributedSampler
    batch_shuffle: true
    batch_size: 2


evaluator_cfg:
  save_name: PSMNet_SceneFlow
  eval_func: OpenStereoEvaluator
  restore_hint: 501
  metric:
    - d1_all
    - epe
    - thres_1
    - thres_2
    - thres_3
  enable_float16: true
  restore_ckpt_strict: true
  show_progress_bar: true
  sampler:
    type: BasicStereoSampler
    batch_shuffle: false
    batch_size: 2
