data_cfg:
  name: SceneFlow
  root: data/SceneFlow
  train_list: datasets/sceneflow/sceneflow_finalpass_train.txt
  val_list: datasets/sceneflow/sceneflow_finalpass_test.txt
  test_list: datasets/sceneflow/sceneflow_finalpass_test.txt
  num_workers: 4

  transform:
    train:
      size: [ 256, 640 ]
      mean: [ 0.485, 0.456, 0.406 ]
      std: [ 0.229, 0.224, 0.225 ]
    test:
      size: [ 576, 960 ]
      mean: [ 0.485, 0.456, 0.406 ]
      std: [ 0.229, 0.224, 0.225 ]


model_cfg:
  model: DSMNet1x

  base_config:
    max_disp: 192

#  # Backbone
#  backbone_cfg:
#    type: GwcNet
#
#  # VolumeCostProcessor
#  cost_processor_cfg:
#    type: GwcVolumeCostProcessor
#
#  # DispProcessor
#  disp_processor_cfg:
#    type: GwcDispProcessor


optimizer_cfg:
  solver: AdamW
  lr: 0.00001
#  betas: [ 0.9, 0.999 ]


loss_cfg:
  - log_prefix: disp0
    type: Smooth_l1_Loss
    loss_term_weight: 0.2
  - log_prefix: disp1
    type: Smooth_l1_Loss
    loss_term_weight: 0.6
  - log_prefix: disp2
    type: Smooth_l1_Loss
    loss_term_weight: 1

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 5000
    - 15000
  scheduler: MultiStepLR


trainer_cfg:
  save_name: DSMNet_SceneFlow
  restore_hint: 0
  restore_ckpt_strict: true
  log_iter: 1
  with_test: true
  enable_float16: false
  fix_BN: false
  sync_BN: false
  save_iter: 10
  total_iter: 20000
  total_epoch: 300
  optimizer_reset: false
  scheduler_reset: false

  sampler:
    type: BasicStereoSampler
    batch_shuffle: false
    batch_size: 1


evaluator_cfg:
  eval_func: OpenStereoEvaluator
  save_name: DSMNet_SceneFlow
  restore_hint: 0
  metric:
    - d1_all
    - epe
    - thres_1
    - thres_2
    - thres_3
  restore_ckpt_strict: true
  enable_float16: false
  fix_BN: false
  sync_BN: false

  sampler:
    type: BasicStereoSampler
    batch_shuffle: false
    batch_size: 1
