data_cfg:
  name: FlyingThings3DSubset
  root: /mnt/nas/public_data/SceneFlow/
  train_list: datasets/SceneFlow/FlyingThings3D_sttr_train.txt
  val_list: datasets/SceneFlow/FlyingThings3D_sttr_test.txt
  test_list: datasets/SceneFlow/FlyingThings3D_sttr_test.txt
  num_workers: 8
  train_batch_size: 1
  val_batch_size: 1
  pin_memory: true
  shuffle: true

  batch_uniform: true
  random_type: range_for_sttr
  #  random_type: range
  #  w_range: [ 0.5, 2.0 ]
  #  h_range: [ 0.5, 2.0 ]
  #  random_type: choice
  #  h_range: [ 256, 288, 320, 352 ]
  #  w_range: [ 480, 512, 544, 576 ]

  transform:
    train:
      - type: RandomCrop
        size: [ 360, 640 ]
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]

    val:
      - type: StereoPad
        size: [ 540, 960 ]
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]

model_cfg:
  model: STTRNet
  _set_static_graph: true
  find_unused_parameters: false
  base_config:
    max_disp: 192
    channel_dim: 128
    position_encoding: sine1d_rel
    num_attn_layers: 6
    nheads: 8
    regression_head: ot
    context_adjustment_layer: cal
    cal_num_blocks: 8
    cal_feat_dim: 16
    cal_expansion_ratio: 4
    downsample: 3
  loss_config:
    px_error_threshold: 3
    validation_max_disp: -1
    loss_weight: 'rr:1.0, l1_raw:1.0, l1:1.0, occ_be:1.0'


loss_cfg:
  # This model uses the user-defined loss function.
  px_error_threshold: 3
  validation_max_disp: 192
  loss_weight: 'rr:1.0, l1_raw:1.0, l1:1.0, occ_be:1.0'


trainer_cfg:
  save_name: STTR-Stereo_FlyingThings3D_subset
  total_epoch: 10
  restore_hint: 0
  log_iter: 50 # iter
  save_every: 1 # epoch
  val_every: 1 # epoch
  amp: false
  sync_bn: true
  fix_bn: false
  init_parameters: false

  optimizer_cfg:
    solver: Adam
    lr: 0.0008
    betas: [ 0.9, 0.999 ]
    lr_backbone: 0.0008
    lr_regression: 0.0016

  scheduler_cfg:
    scheduler: MultiStepLR
    gamma: 0.5
    milestones: [ 5, 7, 9]
    warmup:
      warmup_steps: 2000

  evaluator_cfg:
    metric:
      - d1_all
      - epe
      - bad_1
      - bad_2
      - bad_3

  clip_grad_cfg:
    type: norm
    max_norm: 35
    norm_type: 2
