data_cfg:
  name: SceneFlow
  root: data/SceneFlow
  train_list: datasets/sceneflow/sceneflow_finalpass_train.txt
  val_list: datasets/sceneflow/sceneflow_finalpass_test.txt
  test_list: datasets/sceneflow/sceneflow_finalpass_test.txt
  num_workers: 4

  transform:
    train:
      # size: [ 256, 512 ]
      size: [ 128, 256 ]
      mean: [ 0.485, 0.456, 0.406 ]
      std: [ 0.229, 0.224, 0.225 ]
    test:
      size: [ 512, 960 ]
      mean: [ 0.485, 0.456, 0.406 ]
      std: [ 0.229, 0.224, 0.225 ]


model_cfg:
  model: STTRNet
  _set_static_graph: true
  find_unused_parameters: false
  base_config:
    max_disp: 192
    channel_dim: 128
    position_encoding: sine1d_rel
    num_attn_layers: 6
    nheads: 8
    regression_head: ot
    context_adjustment_layer: cal
    cal_num_blocks: 8
    cal_feat_dim: 16
    cal_expansion_ratio: 4
    downsample: 3
  loss_config:
    px_error_threshold: 3
    validation_max_disp: -1
    loss_weight: 'rr:1.0, l1_raw:1.0, l1:1.0, occ_be:1.0'


optimizer_cfg:
  solver: Adam
  lr: 0.8e-3
  betas: [ 0.9, 0.999 ]
  lr_backbone: 0.8e-3
  lr_regression: 1.6e-3


loss_cfg:
  # This model uses the user-defined loss function.
  px_error_threshold: 3
  validation_max_disp: 192
  loss_weight: 'rr:1.0, l1_raw:1.0, l1:1.0, occ_be:1.0'

scheduler_cfg:
  scheduler: MultiStepLR
  gamma: 0.1
  milestones:
    - 75000


trainer_cfg:
  save_name: STTR-Stereo_SceneFlow
  restore_hint: 0
  restore_ckpt_strict: true
  log_iter: 100
  with_test: true
  enable_float16: false
  sync_BN: true
  save_iter: 50000
  total_iter: 150000
  total_epoch: 20
  optimizer_reset: false
  scheduler_reset: false
  sampler:
    # type: BasicStereoSampler
    batch_shuffle: true
    batch_size: 1


evaluator_cfg:
  eval_func: OpenStereoEvaluator
  save_name: STTR-Stereo_SceneFlow
  restore_hint: 0
  metric:
    - d1_all
    - epe
    - thres_1
    - thres_2
    - thres_3
  restore_ckpt_strict: true
  enable_float16: false
  sampler:
    type: BasicStereoSampler
    batch_shuffle: false
    batch_size: 1
