data_cfg:
  name: SceneFlow
  root: data/SceneFlow
  train_list: datasets/sceneflow/train.txt
  val_list: datasets/sceneflow/test.txt
  test_list: datasets/sceneflow/test.txt
  num_workers: 4

  transform:
    train:
      size: [ 256, 512 ]
      # size: [ 128, 256 ]
      mean: [ 0.485, 0.456, 0.406 ]
      std: [ 0.229, 0.224, 0.225 ]
    test:
      size: [ 512, 960 ]
      mean: [ 0.485, 0.456, 0.406 ]
      std: [ 0.229, 0.224, 0.225 ]


model_cfg:
  model: ACVNet
#  find_unused_parameters: true
  base_config:
    max_disp: 192
    attn_weights_only: False
    freeze_attn_weights: False

optimizer_cfg:
  solver: Adam
  lr: 0.001
  betas: [ 0.9, 0.999 ]


loss_cfg:
  # This model uses the user-defined loss function.

scheduler_cfg:
  scheduler: MultiStepLR
  gamma: 0.1,0.02,0.008
  milestones:
    - 750000,1000000,1500000


trainer_cfg:
  save_name: ACV-Stereo_SceneFlow
  restore_hint: 0
  restore_ckpt_strict: true
  log_iter: 100
  with_test: true
  enable_float16: false
  sync_BN: true
  save_iter: 5000
  total_iter: 2000000
  total_epoch: 100
  optimizer_reset: false
  scheduler_reset: false
  sampler:
    # type: BasicStereoSampler
    batch_shuffle: true
    batch_size: 4


evaluator_cfg:
  eval_func: OpenStereoEvaluator
  save_name: ACV-Stereo_SceneFlow
  restore_hint: 0
  metric:
    - d1_all
    - epe
    - thres_1
    - thres_2
    - thres_3
  restore_ckpt_strict: true
  enable_float16: false
  sampler:
    type: BasicStereoSampler
    batch_shuffle: false
    batch_size: 1
