data_cfg:
  name: KITTI2015
  root: data/kitti15
  train_list: datasets/kitti15/kitti15_train165.txt
  val_list: datasets/kitti15/kitti15_val35.txt
  test_list: datasets/kitti15/kitti15_test.txt
  num_workers: 4


  transform:
    train:
      - type: RandomCrop
        size: [ 256, 512 ]
      #- type: RandomHorizontalFlip
      #  prob: 0.5
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    test:
      - type: StereoPad
        size: [ 384, 1248 ]
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]

model_cfg:
  model: GwcNet

  base_config:
    max_disp: 192
    downsample: 4
    num_groups: 40
    use_concat_volume: True
    concat_channels: 12

  # Backbone
  backbone_cfg:
    type: GwcNet

  # VolumeCostProcessor
  cost_processor_cfg:
    type: GwcVolumeCostProcessor

  # DispProcessor
  disp_processor_cfg:
    type: GwcDispProcessor

optimizer_cfg:
  solver: Adam
  lr: 0.001
  betas: [ 0.9, 0.999 ]


loss_cfg:
  - log_prefix: disp
    type: Weighted_Smooth_l1_Loss
    loss_term_weight: 1
    weights: [ 0.5,0.5,0.7,1.0 ]

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 6000
  scheduler: MultiStepLR
  warmup:
    type: LinearWarmup
    warmup_period: 500

trainer_cfg:
  save_name: GwcNet_kitti15
  restore_hint: 'output/SceneFlow/GwcNet/GwcNet_SceneFlow/checkpoints/GwcNet_SceneFlow-20000.pt'
  restore_ckpt_strict: true
  log_iter: 1
  with_test: true
  enable_float16: false
  save_iter: 200
  sync_BN: true
  total_iter: 20000
  total_epoch: 400
  optimizer_reset: true
  scheduler_reset: true

  sampler:
    batch_shuffle: true
    batch_size: 4


evaluator_cfg:
  eval_func: OpenStereoEvaluator
  save_name: GwcNet_kitti15
  restore_hint: 'output/SceneFlow/GwcNet/GwcNet_SceneFlow/checkpoints/GwcNet_SceneFlow-20000.pt'
  metric:
    - d1_all
    - epe
    - thres_1
    - thres_2
    - thres_3
  enable_float16: False
  restore_ckpt_strict: true

  sampler:
    batch_shuffle: false
    batch_size: 1
