data_cfg:
  name: SceneFlow
  root: data/SceneFlow
  train_list: datasets/SceneFlow/sceneflow_finalpass_train.txt
  val_list: datasets/SceneFlow/sceneflow_finalpass_test_select.txt
  test_list: datasets/SceneFlow/sceneflow_finalpass_test.txt
  num_workers: 16

  batch_uniform: false
  #  random_type: range
  #  w_range: [ 0.5, 2.0 ]
  #  h_range: [ 0.5, 2.0 ]
  #  random_type: choice
  #  h_range: [ 256, 288, 320, 352 ]
  #  w_range: [ 480, 512, 544, 576 ]

  transform:
    train:
      - type: RandomCrop
        size: [ 256, 512 ]
      #- type: RandomHorizontalFlip
      #  prob: 0.5
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
    test:
      - type: TestCrop
        size: [ 512, 960 ]
      - type: GetValidDisp
        max_disp: 192
      - type: TransposeImage
      - type: ToTensor
      - type: NormalizeImage
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]



model_cfg:
  model: CasStereoNet

  base_config:
    max_disp: 192


optimizer_cfg:
  solver: Adam
  lr: 0.001
  betas: [ 0.9, 0.999 ]


loss_cfg:
  type: CasStereoLoss # user defined loss

scheduler_cfg:
  scheduler: MultiStepLR
  gamma: 0.5
  milestones:
    - 40000
    - 50000
    - 60000
    - 70000
  warmup:
    type: LinearWarmup
    warmup_period: 500


trainer_cfg:
  save_name: CasNet_SceneFlow_N
  restore_hint: 0
  restore_ckpt_strict: true
  log_iter: 10
  with_test: true
  enable_float16: false
  sync_BN: false
  save_iter: 4432
  total_iter: 150000
  total_epoch: 18
  optimizer_reset: false
  scheduler_reset: false

  sampler:
    # type: BasicStereoSampler
    batch_shuffle: false
    batch_size: 4


evaluator_cfg:
  eval_func: OpenStereoEvaluator
  save_name: CasNet_SceneFlow_N
  restore_hint: 0
#  show_progress_bar: true
  metric:
    - d1_all
    - epe
    - thres_1
    - thres_2
    - thres_3
  restore_ckpt_strict: true
  enable_float16: false

  sampler:
#    type: BasicStereoSampler
    batch_shuffle: false
    batch_size: 8
